### ISSUE TITLE
Publication in Galaxy

### ISSUE THREAD

**Issue by igormukhingmailcom** [jdauphant/ansible-role-sublimetext#1]
Please, publish this role to galaxy.ansible.com

**Comment by jdauphant** [comment]
Hello,
The role is now available here : https://galaxy.ansible.com/list#/roles/3070

Have a nice day

**Comment by igormukhingmailcom** [comment]
Thank you.

**Comment by igormukhingmailcom** [comment]
Maybe you will be interested in https://galaxy.ansible.com/list#/roles/3078

**Comment by jdauphant** [comment]
Thanks, I will take a look.
For the moment, I don't use packagecontrol.
If I will use it, I will prefer to integrate packages management in my role to limit my number of roles.

**Comment by igormukhingmailcom** [comment]
You're welcome to get my code for that if you need.

**Comment by jdauphant** [comment]
Ok thanks
